const userRoutes = require('./user.routes')
const productRoutes = require('./product.routes')
const cartRoutes = require('./cart.routes')
const checkoutRoutes = require('./checkout.routes')
const orderRoutes = require('./order.routes')
const uploadRoutes = require('./upload.routes')
const subscriberRoutes = require('./subscriber.routes')
const adminRoutes = require('./admin.routes')
const productAdminRoutes = require('./productAdmin.routes')
const adminOrderRoutes = require('./adminOrder.routes')

module.exports.routes = (app) => {
  app.use('/api/users', userRoutes)
  app.use('/api/products', productRoutes)
  app.use('/api/cart', cartRoutes)
  app.use('/api/checkout', checkoutRoutes)
  app.use('/api/orders', orderRoutes)
  app.use('/api/upload', uploadRoutes)
  app.use('/api/subscribe', subscriberRoutes)
  app.use('/api/admin', adminRoutes)
  app.use('/api/admin/products', productAdminRoutes)
  app.use('/api/admin/orders', adminOrderRoutes)
}